### ISSUE TITLE
File systems considerations for beRi.

### ISSUE THREAD

**Issue by grabear** [datasnakes/beRi#9]
# ~~Option 1~~
File system:
![image](https://user-images.githubusercontent.com/20953530/39461141-641efe60-4cce-11e8-97ca-37b96db78a1e.png)

When using _beri install *_, several things will need to be taken into consideration.  
* By default beri will install packages into the main local repository (_**R_LIBS_USER**_) unless specified in some type of configuration file (not yet decided).  
* Using _beri install --project *_ will install a package into a **packrat project** which will be accessible via system links in the projects folder.
* Using _beri install --minicran * --project *_ will download a source package into a miniCRAN repository and then install it into the project.
* Using _beri install --repo * --project *_ will install into a repository and then install it into a project.

# Option 2
File system:
![image](https://user-images.githubusercontent.com/20953530/39461696-3789bd82-4cd2-11e8-915d-3e860969e61c.png)
The same installation parameters will be used with option 2, except _**R_LIBS_USER**_ is the _~/.local/beRi/\*/\<platform\>/<R_version>/libs_ directory.

(**NOTE**:  _This part gets more into the loading of libraries vs installing libraries_)
Option 2's hierarchical nature will also make it easy to chain paths of various package dependencies to an environment variable.  This variable would then be used by the R shell to load specific versions of packages.  This could remove the need for packrat (potentially), the projects directory, and the repos directory.  Instead you could have a configuration file that looks like:

```toml
# File:  ~/.local/beRi/beri.toml

[project.stress_microbiome_analysis]
metacoder=3.3
phyloseq=3.3

[project.rnaseq_analysis]
DESeq2=3.3
edgeR=3.3

[repository.microbiome]
metacoder=3.3
microbiome=3.3
phyloseq=3.3
```
